import { PrismaClient } from '../generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error('DATABASE_URL is not defined');
}

const adapter = new PrismaPg({
  connectionString,
});

const prisma = new PrismaClient({
  adapter,
});

const albums = [
  {
    title: 'Disturbios Barcelona 20/02/2021',
    subtitle: 'Barcelona, febrero de 2021',
    slug: 'bcn-20-02-2021',
    description:
      'Fotorreportaje de los disturbios que acontecieron en Barcelona del 20 de febrero de 2021 a raíz de la detención de Pablo Hasel.',
    coverPhotoUrl:
      'https://res.cloudinary.com/lensbymike/image/upload/v1782140721/IMG_0776_bzyhf1.jpg',
    orderIndex: 3,
    isPublished: true,
    isFeatured: false,
    photos: [
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140748/IMG_0739_dqy7ay.jpg',
        title: 'Disturbios Barcelona 01',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:57:18',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140747/IMG_0750_gvl4yx.jpg',
        title: 'Disturbios Barcelona 02',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:15:49',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140745/IMG_0803_f6hvzo.jpg',
        title: 'Disturbios Barcelona 03',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:25:14',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140744/IMG_0798_i9lviu.jpg',
        title: 'Disturbios Barcelona 04',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:21:04',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140744/IMG_0799_qdjvoi.jpg',
        title: 'Disturbios Barcelona 05',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:22:20',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140743/IMG_0766_j4cvnt.jpg',
        title: 'Disturbios Barcelona 06',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '1000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:29:06',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140742/IMG_0791_idycay.jpg',
        title: 'Disturbios Barcelona 07',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:19:07',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140742/IMG_0753_h0fv9v.jpg',
        title: 'Disturbios Barcelona 08',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:22:32',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140741/IMG_0752_h1zwwz.jpg',
        title: 'Disturbios Barcelona 09',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:22:27',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140739/IMG_0743_im34yx.jpg',
        title: 'Disturbios Barcelona 10',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: true,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:10:28',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140734/IMG_0726_n4j4wo.jpg',
        title: 'Disturbios Barcelona 11',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '1250',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:48:02',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140726/IMG_0720_hsnkz3.jpg',
        title: 'Disturbios Barcelona 12',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:45:44',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140726/IMG_0760_rcpzzt.jpg',
        title: 'Disturbios Barcelona 13',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '1600',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:25:34',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140725/IMG_0707_pkwglr.jpg',
        title: 'Disturbios Barcelona 14',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:37:25',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140725/IMG_0804_dnrgf7.jpg',
        title: 'Disturbios Barcelona 15',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:25:21',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140725/IMG_0754_rzykuy.jpg',
        title: 'Disturbios Barcelona 16',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:23:14',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140724/IMG_0795_ddmdkh.jpg',
        title: 'Disturbios Barcelona 17',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:19:50',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140724/IMG_0793_ajxev2.jpg',
        title: 'Disturbios Barcelona 18',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:19:36',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140723/IMG_0790_pgwebe.jpg',
        title: 'Disturbios Barcelona 19',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:06:49',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140723/IMG_0788_igtd4u.jpg',
        title: 'Disturbios Barcelona 20',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:05:57',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140722/IMG_0765_b1rwcn.jpg',
        title: 'Disturbios Barcelona 21',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '3200',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:28:21',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140722/IMG_0786_x8kpur.jpg',
        title: 'Disturbios Barcelona 22',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '3200',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 22:04:56',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140721/IMG_0776_bzyhf1.jpg',
        title: 'Disturbios Barcelona 23',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '250',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:48:20',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140720/IMG_0734_aaf0wy.jpg',
        title: 'Disturbios Barcelona 24',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:51:31',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140719/IMG_0758_h0jj3h.jpg',
        title: 'Disturbios Barcelona 25',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '4000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:25:02',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140718/IMG_0713_it2oni.jpg',
        title: 'Disturbios Barcelona 26',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/800',
          aperture: 'f/1.8',
          iso: '1600',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:41:08',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140717/IMG_0718_m1ltdg.jpg',
        title: 'Disturbios Barcelona 27',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:45:13',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140716/IMG_0757_mt6fkk.jpg',
        title: 'Disturbios Barcelona 28',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '1250',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:24:37',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140715/IMG_0731_cstp86.jpg',
        title: 'Disturbios Barcelona 29',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '1000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:50:39',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140715/IMG_0728_qwy1ir.jpg',
        title: 'Disturbios Barcelona 30',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '1000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:49:53',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140714/IMG_0736_j7ebfn.jpg',
        title: 'Disturbios Barcelona 31',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:55:57',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140714/IMG_0741_qpjqka.jpg',
        title: 'Disturbios Barcelona 32',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:09:47',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140712/IMG_0744_nbifty.jpg',
        title: 'Disturbios Barcelona 33',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:11:21',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140681/IMG_0749_jfqy6i.jpg',
        title: 'Disturbios Barcelona 34',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:13:49',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140680/IMG_0768_klltzk.jpg',
        title: 'Disturbios Barcelona 35',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '100',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:29:46',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140680/IMG_0770_coj1yf.jpg',
        title: 'Disturbios Barcelona 36',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: true,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '640',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 21:31:05',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140679/IMG_0727_ebycws.jpg',
        title: 'Disturbios Barcelona 37',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '1000',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:48:43',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140679/IMG_0722_gcagca.jpg',
        title: 'Disturbios Barcelona 38',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '800',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:46:57',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140678/IMG_0715_h0wul7.jpg',
        title: 'Disturbios Barcelona 39',
        category: 'reportaje urbano',
        description:
          'Fotografia documental de los disturbios en Barcelona del 20 de febrero de 2021.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/320',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2021:02:20 20:43:56',
        },
      },
    ],
  },
  {
    title: 'ELMS 2023',
    subtitle: 'Circuit de Barcelona-Catalunya, abril de 2023',
    slug: 'elms-2023',
    description:
      'Accion de la European Le Mans Series en el Circuit de Barcelona-Catalunya en 2023.',
    coverPhotoUrl:
      'https://res.cloudinary.com/lensbymike/image/upload/v1781895009/IMG_2678_fgxti9.jpg',
    orderIndex: 2,
    isPublished: true,
    isFeatured: false,
    photos: [
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895070/IMG_3458_ibul9i.jpg',
        title: 'ELMS 2023 Montmeló 01',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '293.0 mm',
          dateTaken: '2023:04:23 14:00:38',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895068/IMG_3459_jhpljx.jpg',
        title: 'ELMS 2023 Montmeló 02',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: true,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '293.0 mm',
          dateTaken: '2023:04:23 14:00:39',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895067/IMG_3351_qucq13.jpg',
        title: 'ELMS 2023 Montmeló 03',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 13:43:05',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895065/IMG_3426_dihojd.jpg',
        title: 'ELMS 2023 Montmeló 04',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1250',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:56:32',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895065/IMG_3397_pvxuvk.jpg',
        title: 'ELMS 2023 Montmeló 05',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/640',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:52:56',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895064/IMG_3450_xxbu8y.jpg',
        title: 'ELMS 2023 Montmeló 06',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/500',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '293.0 mm',
          dateTaken: '2023:04:23 13:59:33',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895063/IMG_3454_fvszg2.jpg',
        title: 'ELMS 2023 Montmeló 07',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '293.0 mm',
          dateTaken: '2023:04:23 14:00:17',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895062/IMG_3414_au7ohq.jpg',
        title: 'ELMS 2023 Montmeló 08',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:55:10',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895061/IMG_3141_ccmcak.jpg',
        title: 'ELMS 2023 Montmeló 09',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: true,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '244.0 mm',
          dateTaken: '2023:04:23 13:06:43',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895058/IMG_2982_gh89zh.jpg',
        title: 'ELMS 2023 Montmeló 10',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 11:27:13',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895058/IMG_2976_vo5o5l.jpg',
        title: 'ELMS 2023 Montmeló 11',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 11:24:22',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895057/IMG_3164_yachu4.jpg',
        title: 'ELMS 2023 Montmeló 12',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:08:29',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895056/IMG_3345_oiob03.jpg',
        title: 'ELMS 2023 Montmeló 13',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 13:41:54',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895054/IMG_3233_rexep6.jpg',
        title: 'ELMS 2023 Montmeló 14',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:16:54',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895052/IMG_3084_amiux1.jpg',
        title: 'ELMS 2023 Montmeló 15',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1250',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 12:55:27',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895051/IMG_3304_a6p4zp.jpg',
        title: 'ELMS 2023 Montmeló 16',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:28:20',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895050/IMG_3338_jlsftf.jpg',
        title: 'ELMS 2023 Montmeló 17',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 13:40:40',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895048/IMG_3285_mpesro.jpg',
        title: 'ELMS 2023 Montmeló 18',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:24:28',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895047/IMG_2972_s42but.jpg',
        title: 'ELMS 2023 Montmeló 19',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 11:21:46',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895047/IMG_3317_v4j0hg.jpg',
        title: 'ELMS 2023 Montmeló 20',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/6.3',
          iso: '100',
          focalLength: '388.0 mm',
          dateTaken: '2023:04:23 13:30:33',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895046/IMG_3197_bmigsq.jpg',
        title: 'ELMS 2023 Montmeló 21',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '252.0 mm',
          dateTaken: '2023:04:23 13:13:09',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895045/IMG_3191_inwbff.jpg',
        title: 'ELMS 2023 Montmeló 22',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '252.0 mm',
          dateTaken: '2023:04:23 13:12:42',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895041/IMG_2961_eecqct.jpg',
        title: 'ELMS 2023 Montmeló 23',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 11:18:18',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895040/IMG_3339_l4ovkj.jpg',
        title: 'ELMS 2023 Montmeló 24',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 13:40:41',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895039/IMG_3226_fktqsv.jpg',
        title: 'ELMS 2023 Montmeló 25',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:16:05',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895039/IMG_3140_ztgxc0.jpg',
        title: 'ELMS 2023 Montmeló 26',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '244.0 mm',
          dateTaken: '2023:04:23 13:06:42',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895037/IMG_3248_dwf1kx.jpg',
        title: 'ELMS 2023 Montmeló 27',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:18:53',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895037/IMG_3021_oasuvx.jpg',
        title: 'ELMS 2023 Montmeló 28',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 12:26:32',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895036/IMG_3190_m4jzbf.jpg',
        title: 'ELMS 2023 Montmeló 29',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '252.0 mm',
          dateTaken: '2023:04:23 13:12:37',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895035/IMG_3075_vdnmir.jpg',
        title: 'ELMS 2023 Montmeló 30',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1250',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 12:52:39',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895034/IMG_3291_eodj6k.jpg',
        title: 'ELMS 2023 Montmeló 31',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:25:37',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895033/IMG_3287_uxdaeq.jpg',
        title: 'ELMS 2023 Montmeló 32',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:24:52',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895032/IMG_2973_gwtnrn.jpg',
        title: 'ELMS 2023 Montmeló 33',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 11:21:53',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895032/IMG_2914_csixoe.jpg',
        title: 'ELMS 2023 Montmeló 34',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: true,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/6.3',
          iso: '100',
          focalLength: '600.0 mm',
          dateTaken: '2023:04:23 11:03:54',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895031/IMG_3270_mb3qab.jpg',
        title: 'ELMS 2023 Montmeló 35',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:22:28',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895030/IMG_2953_vbb7yj.jpg',
        title: 'ELMS 2023 Montmeló 36',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/640',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 11:15:10',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895029/IMG_3152_lo3kh0.jpg',
        title: 'ELMS 2023 Montmeló 37',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:07:37',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895029/IMG_3005_p1zor4.jpg',
        title: 'ELMS 2023 Montmeló 38',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 12:24:20',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895028/IMG_3017_lsjlkb.jpg',
        title: 'ELMS 2023 Montmeló 39',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 12:25:59',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895028/IMG_3276_tvjqtr.jpg',
        title: 'ELMS 2023 Montmeló 40',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:23:02',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895028/IMG_2974_gjckad.jpg',
        title: 'ELMS 2023 Montmeló 41',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/1000',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 11:22:05',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895027/IMG_2805_tqxhj5.jpg',
        title: 'ELMS 2023 Montmeló 42',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/500',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:22 16:56:46',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895018/IMG_2762_xth0xq.jpg',
        title: 'ELMS 2023 Montmeló 43',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:22 16:13:35',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895016/IMG_2688_whynok.jpg',
        title: 'ELMS 2023 Montmeló 44',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/6400',
          aperture: 'f/1.8',
          iso: '100',
          focalLength: '50.0 mm',
          dateTaken: '2023:04:22 10:14:03',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895016/IMG_3225_cvytjj.jpg',
        title: 'ELMS 2023 Montmeló 45',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/800',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '200.0 mm',
          dateTaken: '2023:04:23 13:16:05',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895016/IMG_2918_zcqfec.jpg',
        title: 'ELMS 2023 Montmeló 46',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/400',
          aperture: 'f/6.3',
          iso: '100',
          focalLength: '600.0 mm',
          dateTaken: '2023:04:23 11:04:11',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895011/IMG_2868_bpuaeu.jpg',
        title: 'ELMS 2023 Montmeló 47',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/640',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:22 17:33:03',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895010/IMG_2770_fq1tga.jpg',
        title: 'ELMS 2023 Montmeló 48',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/500',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:22 16:19:37',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895010/IMG_2686_anibbs.jpg',
        title: 'ELMS 2023 Montmeló 49',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/6400',
          aperture: 'f/1.8',
          iso: '100',
          focalLength: '50.0 mm',
          dateTaken: '2023:04:22 10:13:17',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895009/IMG_2679_f8rd3p.jpg',
        title: 'ELMS 2023 Montmeló 50',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/6400',
          aperture: 'f/1.8',
          iso: '100',
          focalLength: '50.0 mm',
          dateTaken: '2023:04:22 10:10:11',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895009/IMG_2678_fgxti9.jpg',
        title: 'ELMS 2023 Montmeló 51',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/6400',
          aperture: 'f/1.8',
          iso: '100',
          focalLength: '50.0 mm',
          dateTaken: '2023:04:22 10:09:53',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895009/IMG_2787_vlzhrd.jpg',
        title: 'ELMS 2023 Montmeló 52',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/400',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:22 16:21:27',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895009/IMG_2660_v6p5vi.jpg',
        title: 'ELMS 2023 Montmeló 53',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: 'EF50mm f/1.8 II',
          shutterSpeed: '1/500',
          aperture: 'f/1.8',
          iso: '100',
          focalLength: '50.0 mm',
          dateTaken: '2023:04:22 09:52:22',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895007/IMG_2903_xrparj.jpg',
        title: 'ELMS 2023 Montmeló 54',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: true,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/500',
          aperture: 'f/5.6',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:23 10:57:51',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895006/IMG_2788_t0c0n8.jpg',
        title: 'ELMS 2023 Montmeló 55',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/400',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:22 16:21:29',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895006/IMG_2820_gfaz0v.jpg',
        title: 'ELMS 2023 Montmeló 56',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/320',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:22 16:59:23',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1781895006/IMG_2786_lif5ii.jpg',
        title: 'ELMS 2023 Montmeló 57',
        category: 'motor',
        description:
          'Fotografia de automovilismo de la European Le Mans Series en Barcelona.',
        isFeatured: false,
        cameraSettings: {
          camera: 'Canon Canon EOS 60D',
          lens: '150-600mm F5-6.3 DG OS HSM | Contemporary 015',
          shutterSpeed: '1/400',
          aperture: 'f/5.0',
          iso: '100',
          focalLength: '150.0 mm',
          dateTaken: '2023:04:22 16:21:26',
        },
      },
    ],
  },
  {
    title: 'MotoGP Catalunya 2026',
    subtitle: 'Circuit de Barcelona-Catalunya, mayo de 2026',
    slug: 'moto-gp-catalonia-2026',
    description:
      'Gran Premio de Catalunya de Moto GP 2026, en el Circuit de Barcelona-Catalunya.',
    coverPhotoUrl:
      'https://res.cloudinary.com/lensbymike/image/upload/v1782140929/_LBM3815_xph40g.jpg',
    orderIndex: 1,
    isPublished: true,
    isFeatured: false,
    photos: [
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140929/_LBM3815_xph40g.jpg',
        title: 'MotoGP Catalunya 2026 01',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: true,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/3200',
          aperture: 'f/4.0',
          iso: '250',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 14:22:09',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140929/_LBM3325_hzto0w.jpg',
        title: 'MotoGP Catalunya 2026 02',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: true,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:37:10',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140928/_LBM2955_dtlyvd.jpg',
        title: 'MotoGP Catalunya 2026 03',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:29:01',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140927/_LBM2958_gzbpjm.jpg',
        title: 'MotoGP Catalunya 2026 04',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:29:04',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140925/_LBM3195_cxf30w.jpg',
        title: 'MotoGP Catalunya 2026 05',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: true,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:34:07',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140924/_LBM2982_danixw.jpg',
        title: 'MotoGP Catalunya 2026 06',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:29:51',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140924/_LBM3479_kzzpiu.jpg',
        title: 'MotoGP Catalunya 2026 07',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '160',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 13:04:58',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140923/_LBM3359_e9gxtj.jpg',
        title: 'MotoGP Catalunya 2026 08',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '160',
          focalLength: '101.0 mm',
          dateTaken: '2026:05:16 09:39:13',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140923/_LBM3191_vxhdzh.jpg',
        title: 'MotoGP Catalunya 2026 09',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: true,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:33:55',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140920/_LBM2822_upzgbl.jpg',
        title: 'MotoGP Catalunya 2026 10',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:20:51',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140920/_LBM3096_xbyqdu.jpg',
        title: 'MotoGP Catalunya 2026 11',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:32:13',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140919/_LBM3093_gvofj2.jpg',
        title: 'MotoGP Catalunya 2026 12',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:32:13',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140918/_LBM3799_ymzr7p.jpg',
        title: 'MotoGP Catalunya 2026 13',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/3200',
          aperture: 'f/4.0',
          iso: '160',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 14:20:27',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140916/_LBM3732_m5tyd1.jpg',
        title: 'MotoGP Catalunya 2026 14',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/3200',
          aperture: 'f/4.0',
          iso: '200',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 14:13:42',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140915/_LBM3625_zv06cc.jpg',
        title: 'MotoGP Catalunya 2026 15',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/3200',
          aperture: 'f/4.0',
          iso: '200',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 13:20:17',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140915/_LBM3624_l8mmfk.jpg',
        title: 'MotoGP Catalunya 2026 16',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: true,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/3200',
          aperture: 'f/4.0',
          iso: '160',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 13:20:16',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140914/_LBM3622_bu9xhf.jpg',
        title: 'MotoGP Catalunya 2026 17',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/3200',
          aperture: 'f/4.0',
          iso: '200',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 13:20:15',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140914/_LBM3464_jrqzhf.jpg',
        title: 'MotoGP Catalunya 2026 18',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 12:56:16',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140913/_LBM3342_cik1nx.jpg',
        title: 'MotoGP Catalunya 2026 19',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:37:32',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782140913/_LBM3337_b9byg9.jpg',
        title: 'MotoGP Catalunya 2026 20',
        category: 'motor',
        description:
          'Fotografia de motociclismo durante el Gran Premio de Catalunya de MotoGP.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M4',
          lens: 'FE 70-200mm F4 G OSS',
          shutterSpeed: '1/2500',
          aperture: 'f/4.0',
          iso: '125',
          focalLength: '200.0 mm',
          dateTaken: '2026:05:16 09:37:28',
        },
      },
    ],
  },
  {
    title: 'Nurburgreen Indoor',
    subtitle: 'Sesion interior, marzo de 2024',
    slug: 'nurburgreen-indoor',
    description:
      'Fotografia de interior de la sesion Nurburgreen de marzo de 2024.',
    coverPhotoUrl:
      'https://res.cloudinary.com/lensbymike/image/upload/v1782141627/_DSC3400-Mejorado-NR-Editar_uehuwa.jpg',
    orderIndex: 4,
    isPublished: true,
    isFeatured: false,
    photos: [
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141632/_DSC3442_rv6kkh.jpg',
        title: 'Sesion interior Nurburgreen 01',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '1000',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 17:37:36',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141630/_DSC3421_zfyvnr.jpg',
        title: 'Sesion interior Nurburgreen 02',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 17:24:07',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141629/_DSC3420_dirapr.jpg',
        title: 'Sesion interior Nurburgreen 03',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '1250',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 17:23:41',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141629/_DSC3462_ueuosi.jpg',
        title: 'Sesion interior Nurburgreen 04',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '4000',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 17:57:06',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141627/_DSC3446-Mejorado-NR-Editar_qrcq62.jpg',
        title: 'Sesion interior Nurburgreen 05',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '1600',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 17:38:57',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141627/_DSC3400-Mejorado-NR-Editar_uehuwa.jpg',
        title: 'Sesion interior Nurburgreen 06',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '2000',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 17:16:37',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141627/_DSC3524-Mejorado-NR-Editar_acsblk.jpg',
        title: 'Sesion interior Nurburgreen 07',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/160',
          aperture: 'f/1.8',
          iso: '2500',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 18:58:07',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141625/_DSC3451_xztphw.jpg',
        title: 'Sesion interior Nurburgreen 08',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '1600',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 17:41:12',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141625/_DSC3473-Mejorado-NR_izgdk0.jpg',
        title: 'Sesion interior Nurburgreen 09',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: true,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '1250',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 18:02:15',
        },
      },
      {
        url: 'https://res.cloudinary.com/lensbymike/image/upload/v1782141624/_DSC3391_pxo8m7.jpg',
        title: 'Sesion interior Nurburgreen 10',
        category: 'evento',
        description: 'Fotografia de interior de la sesion Nurburgreen.',
        isFeatured: false,
        cameraSettings: {
          camera: 'SONY ILCE-7M3',
          lens: 'FE 50mm F1.8',
          shutterSpeed: '1/200',
          aperture: 'f/1.8',
          iso: '500',
          focalLength: '50.0 mm',
          dateTaken: '2024:03:17 17:13:26',
        },
      },
    ],
  },
];

async function main() {
  await prisma.photo.deleteMany();
  await prisma.album.deleteMany();

  for (const album of albums) {
    const { photos, ...albumData } = album;

    const createdAlbum = await prisma.album.create({
      data: albumData,
    });

    await prisma.photo.createMany({
      data: photos.map((photo) => ({
        ...photo,
        albumId: createdAlbum.id,
      })),
    });
  }
}

main()
  .then(async () => {
    console.log('Seed completed');
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
